Create LocalGenie class
cognaize/pycognaize pull request #136
Opened 2024-02-14 14:09 UTC by IngaMelikyan

2024-02-14 14:25 UTC, davidcognaize requested changes

2024-02-14 14:25 UTC, davidcognaize commented on pycognaize/local_genie.py
> +        task_id = task_id_response.json()['taskId']
`task_id_response.raise_for_status()`

2024-02-14 14:25 UTC, davidcognaize commented on pycognaize/local_genie.py
> +        self.base_url = base_url
`self.base_url = base_url.rstrip('/') + '/'`

2024-02-25 14:10 UTC, davidcognaize approved these changes

2024-02-25 14:14 UTC, armen-melkonyan-23 approved these changes

2024-02-25 14:16 UTC, merged